In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
cards = pd.read_csv("Credit Cards.csv").dropna()
cards

,ID,Name,Interest,Reward,Add_fees,Fees,Over_time,Foreign_fees,Fuel,Min_age,...,Welcome,Milestone,Shopping,Dining,Travel,Lounge,Insurance,Cashback,Entertainment,Features
0,1,Flipkart Axis Bank,52.86,0.00,0,1000,1,3.5,0.0,18,...,1,0,1,1,0,1,0,1,0,"Flipkart,Cashback,Shopping"
1,2,Axis Bank My Zone,52.86,0.20,0,1500,1,3.5,1.0,18,...,0,0,1,1,0,1,0,0,1,"Shopping,Dining,Entertainment,Fuel"
2,3,Axis Bank Magnus,42.58,0.20,0,25000,1,2.0,1.0,18,...,1,1,0,1,1,1,1,0,1,"Travel,Insurance,Fuel"
3,4,Axis Bank Reserve,42.58,0.20,0,100000,1,1.5,1.0,18,...,1,0,0,1,1,1,1,0,1,"Travel,Insurance,Fuel,Entertainment"
4,5,Axis Bank Altas,52.86,1.00,0,10500,1,3.5,1.0,18,...,1,0,0,1,1,1,0,0,1,"Travel,Fuel,Rewards,Entertainment"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,71,IndusInd Bank Duo,46.00,0.00,0,649,1,2.0,1.0,18,...,1,0,0,0,0,0,1,0,0,"Insurance,Fuel"
69,72,IndusInd Bank Platinum Visa,46.00,0.85,0,3400,1,3.5,1.0,18,...,1,0,0,0,1,0,1,0,0,"Travel,Rewards,Insurance"
70,73,IndusInd Bank Legend,46.00,0.75,0,10399,1,1.8,1.0,18,...,1,1,0,0,0,1,1,0,0,"Rewards,Insurance,Lounge"
71,74,IndusInd Bank Indulge,46.00,1.00,0,200400,1,1.8,1.0,18,...,0,0,0,0,1,0,1,1,1,"Cashback,Travel,Rewards,Insurance"
72,75,DBS Bank Bajaj Finserv 5X Rewards,42.00,0.25,0,1698,0,3.5,1.0,21,...,0,1,0,0,0,0,0,1,0,"Bajaj Finserv,Rewards,Fuel"

In [ ]:
columns_to_drop = ['Name','Min_age','Min_income','Credit_score','Max_age','Features']
card_clean=cards.drop(columns=columns_to_drop)
card_clean['Freq']=1
card_clean

,ID,Interest,Reward,Add_fees,Fees,Over_time,Foreign_fees,Fuel,Welcome,Milestone,Shopping,Dining,Travel,Lounge,Insurance,Cashback,Entertainment,Freq
0,1,52.86,0.00,0,1000,1,3.5,0.0,1,0,1,1,0,1,0,1,0,1
1,2,52.86,0.20,0,1500,1,3.5,1.0,0,0,1,1,0,1,0,0,1,1
2,3,42.58,0.20,0,25000,1,2.0,1.0,1,1,0,1,1,1,1,0,1,1
3,4,42.58,0.20,0,100000,1,1.5,1.0,1,0,0,1,1,1,1,0,1,1
4,5,52.86,1.00,0,10500,1,3.5,1.0,1,0,0,1,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,71,46.00,0.00,0,649,1,2.0,1.0,1,0,0,0,0,0,1,0,0,1
69,72,46.00,0.85,0,3400,1,3.5,1.0,1,0,0,0,1,0,1,0,0,1
70,73,46.00,0.75,0,10399,1,1.8,1.0,1,1,0,0,0,1,1,0,0,1
71,74,46.00,1.00,0,200400,1,1.8,1.0,0,0,0,0,1,0,1,1,1,1
72,75,42.00,0.25,0,1698,0,3.5,1.0,0,1,0,0,0,0,0,1,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

columns_to_scale = ["Interest", "Fees"]

card_clean[columns_to_scale] = scaler.fit_transform(card_clean[columns_to_scale])
card_clean.head()

,ID,Interest,Reward,Add_fees,Fees,Over_time,Foreign_fees,Fuel,Welcome,Milestone,Shopping,Dining,Travel,Lounge,Insurance,Cashback,Entertainment,Freq
0,1,1.758621,0.0,0,-0.310542,1,3.5,0.0,1,0,1,1,0,1,0,1,0,1
1,2,1.758621,0.2,0,-0.293147,1,3.5,1.0,0,0,1,1,0,1,0,0,1,1
2,3,-0.173252,0.2,0,0.524441,1,2.0,1.0,1,1,0,1,1,1,1,0,1,1
3,4,-0.173252,0.2,0,3.133764,1,1.5,1.0,1,0,0,1,1,1,1,0,1,1
4,5,1.758621,1.0,0,0.019972,1,3.5,1.0,1,0,0,1,1,1,0,0,1,1

In [ ]:
intercept_ss = 3
default_wt = np.array([-0.75, 2.5 ,-0.1 ,-0.2 ,-0.2 ,-0.1 ,0.75 ,0.2,0.25 ,1.0,0.2 ,0.5 ,0.2 ,0.2 ,0.5 ,0.3, 0.25 ])
default_wt.shape

(17,)

wt[6] = fuel,
wt[9] = shopping,
wt[11] = travel,
wt[14] = cashback,
wt[15] = entertainment,
wt[16] = freq

In [ ]:

def top_cards_by_default(n):
  data = cards.copy()
  wt = default_wt.copy()
  wt[16]=2*wt[16]
  card_array=card_clean.drop(columns=['ID'])
  data['Score'] = 2 + card_array.dot(wt)
  order=data[['Name','Score']]
  order = order.sort_values(by='Score', ascending=False)
  print(f"Our {n} top credit cards for average user: ")
  print(order.head(n))

In [ ]:
n = input("Enter a number of cards to be displayed: ")
n = int(n)
top_cards_by_default(n)

Enter a number of cards to be displayed: 6
Our 6 top credit cards for average user:
                      Name     Score
48         AU Bank Zenith+  9.864699
17  HDFC Diners Club Black  8.141320
19     HDFC Bank Millennia  8.018529
27   Amazon Pay ICICI Bank  7.376578
49          AU Bank Zenith  7.047950
61    IndianOil Citi Bank   6.940525

In [ ]:
def satisfaction_score(isFuel,isShp,isTr,isCb,isEn,Fr,ID, isInt):
  wt = default_wt.copy()
  if isInt:
    wt[0]=0.2*wt[0]
  if isFuel:
    wt[6]=2*wt[6]
  if isShp:
    wt[9]=2*wt[9]
  if isTr:
    wt[11]=2*wt[11]
  if isCb:
    wt[14]=2*wt[14]
  if isEn:
    wt[15]=2*wt[15]
  wt[16]=Fr*wt[16]

  arr = card_clean[card_clean['ID'] == ID]
  val = arr.to_numpy()
  val=val.T
  val=val[1:]
  wt_reshaped=wt.reshape(-1,1).T
  dp  = intercept_ss + wt_reshaped.dot(val)
  lower = max(1,round(dp[0][0],1)-0.5)
  upper = min(10,round(dp[0][0],1)+0.5)
  print("\nPredicted score is ",dp[0][0])
  print(f"\nYour expected Satisfaction score is between {lower} and {upper}")

In [ ]:
def get_satisfaction_score():
  for index, row in cards.iterrows():
    print(f"{row['ID']}: {row['Name']}",end="  ")
  id=int(input("\nSelect a card based on the card ID: "))
  name = cards[cards['ID']==id]['Name'].values[0]
  print("You are using ",name)
  isInt = int(input("Do you pay your bills before the due date? '1' for Yes, '0' for No: "))
  print("\nHow frequently do you use your credit card?")
  print("1: Very Rare")
  print("2: Sometimes")
  print("3: Very frequently")
  freq=int(input())
  print("\nFor what purposes do you use your credit card: '1' for Yes, '0' for No")
  isShop = int(input("Online Shopping? "))
  isTr = int(input("Travel and Tickets? "))
  isFuel = int(input("Fuel? "))
  isCb = int(input("Cashback offers? "))
  isEn = int(input("Entertainment(Movies,etc)? "))
  satisfaction_score(isFuel,isShop,isTr,isCb,isEn,freq,id,isInt)

In [ ]:
get_satisfaction_score()

1: Flipkart Axis Bank  2: Axis Bank My Zone  3: Axis Bank Magnus  4: Axis Bank Reserve  5: Axis Bank Altas  6: Axis Bank Neo  7: Axis Bank Vistara Signature  8: Axis Bank Select  9: Indian Oil Axis Bank  10: Axis Bank Privilege  11: IDFC First Bank Select  12: IDFC First Bank Wow  13: IDFC First Bank Wealth  14: IDFC First Bank Classic  15: Club Vistara IDFC First Bank  16: IDFC First Bank Millennia  17: Tata Neu Infinity HDFC Bank  18: HDFC Diners Club Black  20: HDFC Bank Regelia  21: HDFC Bank Millennia  22: HDFC Bank MoneyBack  23: HDFC Regalia Gold  24: HDFC MoneyBack Plus  25: Marriot Bonvoy HDFC Bank  26: Indian Oil HDFC Bank  27: 6E - Rewards Indigo HDFC Bank  28: Swiggy HDFC Bank  29: Amazon Pay ICICI Bank  30: ICICI Bank Coral  31: ICICI Bank Rubyx  32: ICICI Bank Sapphiro  33: HPCL Super Saver  34: ICICI Bank MakeMyTrip Platinum  35: SBI SimplyClick  36: SBI SimplySave  37: SBI Elite  38: BPCL SBI  39: SBI Prime  40: BPCL SBI Octane  41: Air India SBI Signature  42: SBI Cashback  43: Club Vistara SBI  44: American Express Platinum  45: American Express Membership Rewards  46: American Express Platinum Travel  47: American Express SmartEarn  48: American Express Gold  50: AU Bank LIT  51: AU Bank Zenith+  52: AU Bank Zenith  53: AU Bank Vetta  54: Standard Chartered Ultimate  55: Standard Chartered Digi Smart  56: Standard Chartered Ease My Trip  57: Standard Chartered Smart  58: Standard Chartered Super Value Titanium  59: RBL Bank Shoprite  60: RBL Bank World Safari  61: Bajaj Finserv RBL Bank Binge Supercard  62: RBL Bank Platinum Maxima  63: Citi Bank PremierMiles  64: IndianOil Citi Bank   65: Citi Bank CashBack  66: Citi Bank Rewards  67: Kotak Indigo Ka-Ching 6E Rewards  68: Myntra Kotak  69: Kotak League Platinum  70: Kotak Royale Signature  71: IndusInd Bank Duo  72: IndusInd Bank Platinum Visa  73: IndusInd Bank Legend  74: IndusInd Bank Indulge  75: DBS Bank Bajaj Finserv 5X Rewards
Select a card based on the card ID: 18
You are using  HDFC Diners Club Black
Do you pay your bills before the due date? '1' for Yes, '0' for No: 1

How frequently do you use your credit card?
1: Very Rare
2: Sometimes
3: Very frequently
3

For what purposes do you use your credit card: '1' for Yes, '0' for No
Online Shopping? 1
Travel and Tickets? 1
Fuel? 1
Cashback offers? 1
Entertainment(Movies,etc)? 1

Predicted score is  8.728846221530558

Your expected Satisfaction score is between 8.2 and 9.2

In [ ]:
def recommender():
  age = int(input("Enter your age: "))
  if age < 18 :
    print("Sorry no available cards for you :)")
    return
  income = int(input("Enter your income in LPA: "))
  credit_score=int(input("Enter your credit score (Some companies want credit score of their users to be higher. Write 0 if you dont want to reveal): "))
  eligible_cards = cards[
    (cards['Min_age'] <= age) &
    (cards['Max_age'] >= age) &
    (cards['Min_income'] <= income) &
    (cards['Credit_score'] <= credit_score)
  ]
  eligible_ids = eligible_cards['ID'].tolist()
  if(len(eligible_cards)==0):
    print("Sorry no available cards for you :)")
    return
  isInt = int(input("Do you pay your bills before the due date? '1' for Yes, '0' for No: "))
  print("\nHow frequently will you use your credit cards?")
  print("1: Very Rare")
  print("2: Sometimes")
  print("3: Very frequently")
  Fr=int(input())
  print("\nFor what purposes will you use your credit card: '1' for Yes, '0' for No")
  isShp = int(input("Online Shopping? "))
  isTr = int(input("Travel and Tickets? "))
  isFuel = int(input("Fuel? "))
  isCb = int(input("Cashback offers? "))
  isEn = int(input("Entertainment(Movies,etc)? "))
  wt = default_wt.copy()
  if isInt:
    wt[0]=0.2*wt[0]
  wt[16]=Fr*wt[16]
  if isFuel:
    wt[6]=2*wt[6]
  if isShp:
    wt[9]=2*wt[9]
  if isTr:
    wt[11]=2*wt[11]
  if isCb:
    wt[14]=2*wt[14]
  if isEn:
    wt[15]=2*wt[15]

  card_array=card_clean.drop(columns=['ID'])
  score = card_array.dot(wt)
  result = cards[['ID', 'Name']].copy()
  result['score'] = score
  result = result.sort_values(by='score', ascending=False)
  eligible_cards = result[result['ID'].isin(eligible_ids)]
  final_cards = eligible_cards['Name'].tolist()
  m = len(final_cards)
  if(m==0):
    print("Sorry no available cards for you :)")
  else:
    n = int(input("How many cards do you want us to recommend: "))
    print("\nRecommended cards is/are :")
    for i in range(min(m,n)):
      print(final_cards[i])

In [ ]:
recommender()

Enter your age: 19
Enter your income in LPA: 0
Enter your credit score (Some companies want credit score of their users to be higher. Write 0 if you dont want to reveal): 0
Do you pay your bills before the due date? '1' for Yes, '0' for No: 1

How frequently will you use your credit cards?
1: Very Rare
2: Sometimes
3: Very frequently
2

For what purposes will you use your credit card: '1' for Yes, '0' for No
Online Shopping? 1
Travel and Tickets? 1
Fuel? 1
Cashback offers? 1
Entertainment(Movies,etc)? 1
How many cards do you want us to recommend: 5

Recommended cards is/are :
Air India SBI Signature
ICICI Bank MakeMyTrip Platinum
Myntra Kotak
IndusInd Bank Platinum Visa
Club Vistara SBI

In [ ]:
cards_sorted = cards[['ID','Name','Interest','Features']]
cards_sorted

In [ ]:
cards_sorted[['Feature1', 'Feature2', 'Feature3', 'Feature4', 'Feature5']] = cards_sorted['Features'].str.split(',', expand=True)
cards_sorted

In [ ]:
cards_sorted['Feature5'].values

In [ ]:
cards_sorted=cards_sorted.drop(columns=['Features'])
cards_sorted

In [ ]:
wt = default_wt.copy()
wt[16]=2*wt[16]
card_array=card_clean.drop(columns=['ID'])
cards_sorted['Score'] = 2 + card_array.dot(wt)
cards_sorted

In [ ]:
cards_sorted = cards_sorted.sort_values(by='Score', ascending=False)
cards_sorted

In [ ]:
cards_sorted = cards_sorted.drop(columns=['Score'])
cards_sorted

In [ ]:
cards_sorted.to_csv('cards_ranked.csv', index=False)